# Generated by Django 4.2.11 on 2024-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_details", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("vendor_code", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
