# Generated by Django 4.2.11 on 2024-05-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=50)),
                ("vendor_reference", models.CharField(max_length=100)),
                ("order_date", models.DateField()),
                ("items", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
